//
//  mach_trap_x64.c
//  iblessing-core
//
//  Created by bxl on 2021/11/29.
//  Copyright © 2021 soulghost. All rights reserved.
//

#include "mach_traps.h"

kern_return_t
kern_invalid(__unused void *args)
{
    return KERN_INVALID_ARGUMENT;
}

const mach_trap_t       mach_trap_table[MACH_TRAP_TABLE_COUNT] = {
/* 0 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 1 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 2 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 3 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 4 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 5 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 6 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 7 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 8 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 9 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 10 */ MACH_TRAP(_kernelrpc_mach_vm_allocate_trap, 4, 5, munge_wwlw),
/* 11 */ MACH_TRAP(_kernelrpc_mach_vm_purgable_control_trap, 4, 5, munge_wlww),
/* 12 */ MACH_TRAP(_kernelrpc_mach_vm_deallocate_trap, 3, 5, munge_wll),
/* 13 */ MACH_TRAP(task_dyld_process_info_notify_get, 2, 4, munge_ll),
/* 14 */ MACH_TRAP(_kernelrpc_mach_vm_protect_trap, 5, 7, munge_wllww),
/* 15 */ MACH_TRAP(_kernelrpc_mach_vm_map_trap, 6, 8, munge_wwllww),
/* 16 */ MACH_TRAP(_kernelrpc_mach_port_allocate_trap, 3, 3, munge_www),
/* 17 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 18 */ MACH_TRAP(_kernelrpc_mach_port_deallocate_trap, 2, 2, munge_ww),
/* 19 */ MACH_TRAP(_kernelrpc_mach_port_mod_refs_trap, 4, 4, munge_wwww),
/* 20 */ MACH_TRAP(_kernelrpc_mach_port_move_member_trap, 3, 3, munge_www),
/* 21 */ MACH_TRAP(_kernelrpc_mach_port_insert_right_trap, 4, 4, munge_wwww),
/* 22 */ MACH_TRAP(_kernelrpc_mach_port_insert_member_trap, 3, 3, munge_www),
/* 23 */ MACH_TRAP(_kernelrpc_mach_port_extract_member_trap, 3, 3, munge_www),
/* 24 */ MACH_TRAP(_kernelrpc_mach_port_construct_trap, 4, 5, munge_wwlw),
/* 25 */ MACH_TRAP(_kernelrpc_mach_port_destruct_trap, 4, 5, munge_wwwl),
/* 26 */ MACH_TRAP(mach_reply_port, 0, 0, NULL),
/* 27 */ MACH_TRAP(thread_self_trap, 0, 0, NULL),
/* 28 */ MACH_TRAP(task_self_trap, 0, 0, NULL),
/* 29 */ MACH_TRAP(host_self_trap, 0, 0, NULL),
/* 30 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 31 */ MACH_TRAP(mach_msg_trap, 7, 7, munge_wwwwwww),
/* 32 */ MACH_TRAP(mach_msg_overwrite_trap, 8, 8, munge_wwwwwwww),
/* 33 */ MACH_TRAP(semaphore_signal_trap, 1, 1, munge_w),
/* 34 */ MACH_TRAP(semaphore_signal_all_trap, 1, 1, munge_w),
/* 35 */ MACH_TRAP(semaphore_signal_thread_trap, 2, 2, munge_ww),
/* 36 */ MACH_TRAP(semaphore_wait_trap, 1, 1, munge_w),
/* 37 */ MACH_TRAP(semaphore_wait_signal_trap, 2, 2, munge_ww),
/* 38 */ MACH_TRAP(semaphore_timedwait_trap, 3, 3, munge_www),
/* 39 */ MACH_TRAP(semaphore_timedwait_signal_trap, 4, 4, munge_wwww),
/* 40 */ MACH_TRAP(_kernelrpc_mach_port_get_attributes_trap, 5, 5, munge_wwwww),
/* 41 */ MACH_TRAP(_kernelrpc_mach_port_guard_trap, 4, 5, munge_wwlw),
/* 42 */ MACH_TRAP(_kernelrpc_mach_port_unguard_trap, 3, 4, munge_wwl),
/* 43 */ MACH_TRAP(mach_generate_activity_id, 3, 3, munge_www),
/* 44 */ MACH_TRAP(task_name_for_pid, 3, 3, munge_www),
/* 45 */ MACH_TRAP(task_for_pid, 3, 3, munge_www),
/* 46 */ MACH_TRAP(pid_for_task, 2, 2, munge_ww),
/* 47 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 48 */ MACH_TRAP(macx_swapon, 4, 5, munge_lwww),
/* 49 */ MACH_TRAP(macx_swapoff, 2, 3, munge_lw),
/* 50 */ MACH_TRAP(thread_get_special_reply_port, 0, 0, NULL),
/* 51 */ MACH_TRAP(macx_triggers, 4, 4, munge_wwww),
/* 52 */ MACH_TRAP(macx_backing_store_suspend, 1, 1, munge_w),
/* 53 */ MACH_TRAP(macx_backing_store_recovery, 1, 1, munge_w),
/* 54 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 55 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 56 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 57 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 58 */ MACH_TRAP(pfz_exit, 0, 0, NULL),
/* 59 */ MACH_TRAP(swtch_pri, 0, 0, NULL),
/* 60 */ MACH_TRAP(swtch, 0, 0, NULL),
/* 61 */ MACH_TRAP(thread_switch, 3, 3, munge_www),
/* 62 */ MACH_TRAP(clock_sleep_trap, 5, 5, munge_wwwww),
/* 63 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 64 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 65 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 66 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 67 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 68 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 69 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 70 */ MACH_TRAP(host_create_mach_voucher_trap, 4, 4, munge_wwww),
/* 71 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 72 */ MACH_TRAP(mach_voucher_extract_attr_recipe_trap, 4, 4, munge_wwww),
/* 73 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 74 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 75 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 76 */ MACH_TRAP(_kernelrpc_mach_port_type_trap, 3, 3, munge_wwww),
/* 77 */ MACH_TRAP(_kernelrpc_mach_port_request_notification_trap, 7, 7, munge_wwwwwww),
/* 78 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 79 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 80 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 81 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 82 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 83 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 84 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 85 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 86 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 87 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 88 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 89 */ MACH_TRAP(mach_timebase_info_trap, 1, 1, munge_w),
/* 90 */ MACH_TRAP(mach_wait_until, 1, 2, munge_l),
/* 91 */ MACH_TRAP(mk_timer_create, 0, 0, NULL),
/* 92 */ MACH_TRAP(mk_timer_destroy, 1, 1, munge_w),
/* 93 */ MACH_TRAP(mk_timer_arm, 2, 3, munge_wl),
/* 94 */ MACH_TRAP(mk_timer_cancel, 2, 2, munge_ww),
/* 95 */ MACH_TRAP(mk_timer_arm_leeway, 4, 6, munge_wlll),
/* 96 */ MACH_TRAP(debug_control_port_for_pid, 3, 3, munge_www),
/* 97 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 98 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 99 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* traps 100-107 reserved for IOKit */
/* 100 */ MACH_TRAP(iokit_user_client_trap, 8, 8, munge_wwwwwwww),
/* 101 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 102 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 103 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 104 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 105 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 106 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 107 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 108 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 109 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 110 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 111 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 112 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 113 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 114 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 115 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 116 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 117 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 118 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 119 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 120 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 121 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 122 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 123 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 124 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 125 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 126 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
/* 127 */ MACH_TRAP(kern_invalid, 0, 0, NULL),
};
