name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: update submodules
      run:  git submodule foreach update
    - name: show files
      run:  ls submodules/capstone
    - name: cmake
      run: ./compile-cmake.sh
