name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: cmake
      run: ./compile-cmake.sh
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: cmake
      run: ./compile-cmake.sh && ./run-test.sh

