name: C/C++ CI

on:
  push:
    branches: [ pre-master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: ./compile-cmake.sh
